Added pets: Allay, Axolotl, Warden, Fox, Bee, Goat
BlockHorizons/BlockPets pull request #250
Opened 2022-06-24 03:09 UTC by DavidGlitch04

2022-06-25 08:59 UTC, Ifera requested changes
Thanks for the PR. I have left a couple of reviews, please do review them.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/AllayPet.php
> +	const NETWORD_ID = self::ALLAY;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/AxolotlPet.php
> +	const NETWORD_ID = self::AXOLOTL;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/BeePet.php
> +	const NETWORD_ID = self::BEE;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/FoxPet.php
> +	const NETWORD_ID = self::FOX;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/GoatPet.php
> +	const NETWORD_ID = self::GOAT;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/creatures/WardenPet.php
> +	const NETWORD_ID = self::WARDEN;
`NETWORD_ID` is not needed here (also has a typo). Please remove this.

2022-06-25 08:59 UTC, Ifera commented on src/BlockHorizons/BlockPets/pets/BasePet.php
> +	public const WARDEN = "minecraft:warden";
It would be better if these constants were moved to a separate class (interface preferred e.g. `PetIds`) and then `BasePet` implementing that class.

2022-06-26 00:26 UTC, DavidGlitch04 commented
I have completed the reviews, please review again!

2022-06-26 00:29 UTC, closed without merging